-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-04-14 22:24:04 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE company (
    company_name   VARCHAR2(50) NOT NULL,
    country        VARCHAR2(10)
);

ALTER TABLE company ADD CONSTRAINT company_pk PRIMARY KEY ( company_name );

CREATE TABLE company_film (
    company_company_name   VARCHAR2(50) NOT NULL,
    film_film_name         VARCHAR2(50) NOT NULL,
    film_director          VARCHAR2(30) NOT NULL
);

ALTER TABLE company_film
    ADD CONSTRAINT company_film_pk PRIMARY KEY ( company_company_name,
                                                 film_film_name,
                                                 film_director );

CREATE TABLE film (
    film_name   VARCHAR2(50) NOT NULL,
    director    VARCHAR2(30) NOT NULL,
    year        NUMBER(4),
    score       NUMBER(3, 1),
    budget      NUMBER(10, 1)
);

ALTER TABLE film ADD CONSTRAINT film_pk PRIMARY KEY ( film_name,
                                                      director );

CREATE TABLE film_genre (
    film_film_name     VARCHAR2(50) NOT NULL,
    film_director      VARCHAR2(30) NOT NULL,
    genre_genre_name   VARCHAR2(20) NOT NULL
);

ALTER TABLE film_genre
    ADD CONSTRAINT film_genre_pk PRIMARY KEY ( film_film_name,
                                               film_director,
                                               genre_genre_name );

CREATE TABLE genre (
    genre_name VARCHAR2(20) NOT NULL
);

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( genre_name );

ALTER TABLE company_film
    ADD CONSTRAINT company_film_company_fk FOREIGN KEY ( company_company_name )
        REFERENCES company ( company_name );

ALTER TABLE company_film
    ADD CONSTRAINT company_film_film_fk FOREIGN KEY ( film_film_name,
                                                      film_director )
        REFERENCES film ( film_name,
                          director );

ALTER TABLE film_genre
    ADD CONSTRAINT film_genre_film_fk FOREIGN KEY ( film_film_name,
                                                    film_director )
        REFERENCES film ( film_name,
                          director );

ALTER TABLE film_genre
    ADD CONSTRAINT film_genre_genre_fk FOREIGN KEY ( genre_genre_name )
        REFERENCES genre ( genre_name );
